---
- hosts: 10.154.0.7
  gather_facts: flase
  become: true  
  tasks:
  - name: install wget
    yum:
        name: wget
        state: present

  - name: Download Java
    yum:
        name: java
        state: present

  - name: download jenkins.repo
    get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: install jenkins
    yum:
        name: jenkins
        state: present

  - name: start jenkins
    systemd:
        name: jenkins
        state: started
  - name: enable jenkins
    systemd:
        name: jenkins
        enabled: true
...

