---
- hosts: 10.154.0.3
  tasks:
  - name: Set-up git
    yum:
        name: git
        state: latest
    become: true

  - name: Git clone
    git:
     repo: 'https://github.com/sabeehah123/python-http-server.git'
     dest: python-server
     clone: yes
     update: no

#    command: "git clone https://github.com/sabeehah123/python-http-server.git"

  - name: Git configure
    git_config:
     name: user.name
     value: sabeehah123
     name: user.email
     value: sabeehah1996@gmail.com
    become: true
...
